# Generated by Django 5.1 on 2024-08-16 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_comment_like"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
